image: weboaks/node-karma-protractor-chrome

stages:
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - yarn install

lint:
  stage: test
  tags:
    - docker
  script:
    - npm run lint

test:
  stage: test
  tags:
    - docker
  script:
    - npm run test:coverage

build:
  stage: build
  tags:
    - docker
  script:
    - npm run build
  artifacts:
    paths:
      - dist

pages:
  stage: deploy
  tags:
      - docker
  script:
    - npm run build:pages
  environment:
    name: staging
    url: https://olivierl.gitlab.io/playground
  artifacts:
    paths:
      - public
  only:
    - master