image: olivierl/chromium-xvfb-node:1.0.0

stages:
  - test
  - build
  - deploy

before_script:
  - yarn install

lint:
  stage: test
  tags:
    - docker
  script:
    - yarn run lint

test:
  stage: test
  tags:
    - docker
  script:
    - yarn run test:coverage

build:
  stage: build
  tags:
    - docker
  script:
    - yarn run build
  artifacts:
    paths:
      - dist

pages:
  stage: deploy
  tags:
      - docker
  script:
    - yarn run build:pages
  environment:
    name: staging
    url: https://olivierl.gitlab.io/playground
  artifacts:
    paths:
      - public
  only:
    - master