# image: kadadev/node6-karma-chrome

stages:
  - test
  - build

cache:
  paths:
    - node_modules/

before_script:
  - npm install

lint_job:
  stage: test
  script:
    - npm run lint

test_job:
  stage: test
  script:
    - npm run test:coverage

build_job:
  stage: build
  script:
    - npm run build