version: 2
jobs:
  build:
    docker:
      - image: olivierl/chromium-xvfb-node:1.0.0
      
    working_directory: /usr/src/app
    steps:
      - checkout
      - run: yarn install
      - run: yarn run lint
      - run: yarn run test:coverage
      - run: yarn run build
      - store_artifacts:
          path: dist/
          destination: app
      - store_test_results:
          path: coverage/